cli/package.json
the command name was `corgiTest`, should be `corgi`. This would have broken any usage of the `corgi` command when using a global install.
=> fix bin name

cli/templates/project/src/styles/helpers/_helpers-images.scss
Image helpers referenced an undefined SASS function `percent-ratio-css-vars`. Fixed by importing `helpers-math.scss`
=> image helpers: add missing import

.gitignore, cli/.npmignore, cli/package.json, cli/templates/project/.gitignore, package-lock.json
This adds an explicit `.npmignore` which does _not_ include `.gitignore`. This is so that we have a gitignore when bootstrapping a new project.
=> Bugfix: CLI: project template gitignore is ignored by NPM

cli/templates/project/jsconfig.json
The goal of this PR is to provide a better developer experience by enabling VS Code and other editors to read the aliases we have setup so we can do things like:
- command+click a path to go to it's file
- right click and be able to go to definition
- and more
=> feature: clickable path aliases

cli/templates/project/next-sitemap.js
Removes the default locale from the _explicit_ root path, i.e. `mywebsite.com/en-us/` when the default locale is `en-us`. This way, we don't have two entries for the same page: `/` and `/en-us`
Fixes #29
=> Sitemap: ignore defaultLocale root path

cli/templates/project/src/styles/helpers/_helpers-images.scss
This fixes the missing -webkit prefix on our image-set mixin.
Note that this does not solve the problem mentioned in #34, since Stylelint is an addon via a custom project template. Will address that issue separately, in that repo.
=> fix(image helpers): add -webkit prefix to @image-set SASS mixin.

cli/bin/commands/project.js, cli/bin/index.js, cli/consts.js, cli/lib/merge-package-properties.js
- Compartmentalizes the _current_ corgi project config into a `"package"` property. This is in anticipation of future updates where we have some other custom config settings to add which are not related in any way to package.json.
- Removes the restriction of specific properties that you're allowed to add to your `corgi-project.config.json`. Previously you were only allowed to alter `scripts`, `name`, `dependencies`, and `devDependencies`. You're now free to add whatever you want to be merged into the project's package.json.
- `cd` into your corgi repo
- run the project command locally via `node cli/bin/index.js project my-test-project`
- when prompted for a GitHub template, paste this in: `https://github.com/wethegit/corgi-private-templates/tree/feature/new-config-structure` (this is a …
=> Separate package JSON config from other potential configs

cli/templates/project/src/utils/classnames.js
This simplifies the `classname` function and ensures that nested arrays are flattened
This helps with instances where we are uncertain if a component is using the `classnames` function and the `className` prop can either be a string or an array.
For example:
```jsx
// image you have a component that takes a className
// instead of doing this
<Component
className={className && classnames(Array.isArray(className) ? className : [className])}
/>
// you can simply pass the prop to classnames and it will take care of it
<Component
className={classnames(className)}
/>
```
Also helps avoid this:
```jsx
<Component
className={
classnames([
'regular-classname',
className && className
])
}
/>
// can simply pass the prop with everything else
<Component
className={classnames(['base-classname', …
```
=> feature: improves classname util

cli/package.json, cli/templates/project/.eslintrc.yml
The grouping where actually wrong. The aliases were being reordered to be **after** relative paths, when they should actually be **before** and within their own grouping.
=> fix: eslint alias group

cli/templates/project/src/config-locales.js, cli/templates/project/src/utils/page-setup.js
This small fix to page setup ensures that we are configuring our locales instead of basing ourselves on the files inside the locales directory.  
The main reason being that it removes ambiguity.  
The app is split between two sources of truth when it comes to locales at the moment.
`config-locales.js` is used to generate `alternate` lang metas and also provide data to other areas of the app like in the `_document` and `link` components.
But when it comes to generating the pages we use the `locales` directory as our source of truth instead. 
Also this change:
1. Ensures that locale paths are set so we don't get `undefined`s in the source code
2. Only builds locales that are configured, creating an extra layer in avoiding leaking any unfinished `yaml`s
3. Ensures that `config-locales` is …
=> fix: ensures locale config is source of truth

cli/templates/project/src/context/locale-context.js, cli/templates/project/src/utils/page-setup.js
Removes the `pageSlug` variable from a page's props. 
This variable was added a long time ago, for some project-specific needs, and it does not warrant being part of the framework.
=> chore(project template): remove pageSlug from page props

cli/package.json, cli/templates/page.js, cli/templates/project/next.config.js, cli/templates/project/package.json, cli/templates/project/src/pages/[locale]/index.jsx, cli/templates/project/src/pages/[locale]/subpage/index.jsx, cli/templates/project/src/utils/page-setup.js, docs/docs/pages/page-components.mdx, package-lock.json
Goal of this PR is to get is closer to how we do things on NOA's infrastructure and also improve DX by having YAML files as part of the module system, so we get auto refresh!
1. clone and checkout `fix/removes-glob`
2. run `node cli/bin/index.js project test-yml-modules`
3. `cd` into the new directory, install deps, and open the local server.
=> feature: modulify yml files

cli/lib/check-existing.js, cli/lib/utils.js
Ensure component names are parsed into kebab-case "slugs" as expected. For example, `FAQSection` should now return `faq-section`.
Fixes #66 
- clone this repo and check out the `bugfix/cli-parse-kebab-case` branch.
- run `node cli/bin/index.js project test-kebab-casing`
- run `cd test-kebab-casing`
- run `node ../cli/bin/index.js page FAQSection`
- Note the name of the resulting page directory is `faq-section`.
=> refactor(CLI): make kebab case converter more robust

cli/templates/project/src/layouts/home/components/home-body/home-body.jsx
addresses issue in the `corgi-private-templates` repo https://github.com/wethegit/corgi-private-templates/issues/26
removing the inner duplicate to maintain the anchor link attached to `#main-content`
=> fix: remove main tag from home body causing duplicate main tags in DOM

cli/templates/project/.husky/pre-commit, cli/templates/project/package.json
Adds `lint-staged` as default project template.  
Yes, we want that in EVERY project so we can minimize build-time errors as much as possible.
=> feature: adds lint staged

cli/lib/print-next-steps.js
The instructions for initializing the wethegit component library are missing the @wethegit namespace
Change the messaging to point to `npx @wethegit/component-library init` (and `add`).
Closes #108
=> fix(CLI): ensure component lib CLI outputs correct instructions

cli/templates/project/README.md
The `Project readme` that comes along with a bootstrapped corgi project has some bad intel re: running a project locally.
Changed this to `npm start`
Does this fix any open issues?
Closes #109
=> fix(CLI templates): update project readme with correct local dev command

cli/templates/project/src/pages/_document.jsx
This PR fixes the issue of the html tag's `lang` attribute always being set to the default locale's value.
We're now pulling `pageProps` from within `_document.js`, in order to derive the current locale's slug at such a high level. This is then used as the priority when checking for the `language` string value. It will fall back to the default locale if undefined.
- I'm grabbing the `__NEXT_DATA__` prop from the `Document` component, in order to pull this value. This _seems_ to be fine, but please chime in if you disagree.
- Fixes #121 
existing dev site vs. local (current change)
- pull the `bugfix/html-lang-attr` branch down
- from within the repo's root directory, run the following command: `node ./bin/index.js project testing-html-lang`
- follow the instructions provided by the corgi …
=> Fix [project template] incorrect HTML lang attribute

cli/templates/project/src/layouts/home/components/home-header/home-header.jsx
This simply removes some left-over CSS classnames which added various margin values to the `<HomeHeader>` component. Since the latest major corgi update, style opinions like this are no longer relevant.
=> HomeHeader: Remove non-existent spacing utils

cli/templates/project/package.json, docs/package.json, package-lock.json
- Upgrades the base corgi template to use `v3.0.1` of `@wethegit/react-hooks`.
- Includes a couple dependabot updates which are already in `main`.
This has potential to be a breaking change for anyone expecting the API from v2.x of the hooks library, so I'm requesting to merge this into our upcoming major release
=> Upgrade @wethegit/react-hooks

cli/package.json, cli/templates/project/next.config.js, package-lock.json
Time tracking: https://wethecollective.teamwork.com/app/tasks/25651481
This fixes an issue that was introduced with Next 14 due to its use of Webpack 5. Webpack no longer polyfills core Node.js modules ("fs" for example), so it became necessary to do this manually. [Reference](https://webpack.js.org/configuration/resolve/#resolvefallback). This was build-breaking, and rendered Corgi unusable.
Fixes #201 
This bumps the corgi CLI to `4.0.2`
=> [Project template] Bugfix: Introduce fallbacks for core node modules in browser
